apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terasky-argocd-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: terasky
  source:
    repoURL: git@github.com:dpentim78/argocd-terasky-config.git
    path: dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true